### PR TITLE
Backproj pp review

### PR DESCRIPTION
**Pull request by payno**
- [x] check PEP8
- [x] check some use cases succeed in my computer
- [x] check doc generated
- [x] check API

### CODE REVIEW

**Comment by payno** [comment]
functions `fourier_filter` and `filter_projection` in 'backprojection.py' have been removed but here since 0.6.
It would be better to deprecated then for a few release if possible.

**Comment by payno** [comment]
Maybe some function like `init_geometry`, `allocate_memory`, 'init_kernel' ... shouldn't be 'public' to keep hand free for future refactoring... ? For the Backprojection and the SinoFilter classes

**Comment by pierrepaleo** [comment]
Thanks for the review and adds.
`fourier_filter` and `filter_projection` are actually calling the same function, as `gpyfft` was disabled.
In this refactoring, the equivalent is `self.sino_filter(sino)`.
But you are right, we should keep these with a deprecation warning.
Regarding the private/public initialization functions, perhaps they should indeed be kept "private".

**Comment by payno** [comment]
Work well on my PC :+1:

**Comment by payno** [comment]
Maybe on the future the 'apodization' dictionary could be defined at the root level and we could have a get_available_filters() or something like that. 

Could be usefull for gui, unit test...

**Comment by pierrepaleo** [comment]
Thanks ! I'll make the modifications you suggested

**Pull request merged**
